/**
 * Nigerian delivery location seed data (operational).
 *
 * Scope:
 * - All 36 states + FCT
 * - LGA lists for each state (standard administrative LGAs)
 * - Towns/cities: each LGA gets its administrative seat (LGA name) plus curated
 *   major towns where listed. This is NOT a complete national gazetteer of every
 *   village/hamlet — document that limitation in the Stage 09 review.
 *
 * Format: { code, name, lgas: [{ code, name, towns?: string[] }] }
 * When towns is omitted, the LGA name is used as the sole town/city option.
 */

export type SeedLga = { code: string; name: string; towns?: string[] };
export type SeedState = { code: string; name: string; lgas: SeedLga[] };

function lgas(names: string[]): SeedLga[] {
  return names.map((name) => ({
    code: name
      .toUpperCase()
      .replace(/[^A-Z0-9]+/g, '_')
      .replace(/^_|_$/g, ''),
    name,
  }));
}

function lgasWithTowns(
  entries: Array<{ name: string; towns: string[] }>,
): SeedLga[] {
  return entries.map((e) => ({
    code: e.name
      .toUpperCase()
      .replace(/[^A-Z0-9]+/g, '_')
      .replace(/^_|_$/g, ''),
    name: e.name,
    towns: e.towns,
  }));
}

export const NIGERIA_LOCATION_SEED: SeedState[] = [
  {
    code: 'AB',
    name: 'Abia',
    lgas: lgas([
      'Aba North',
      'Aba South',
      'Arochukwu',
      'Bende',
      'Ikwuano',
      'Isiala Ngwa North',
      'Isiala Ngwa South',
      'Isuikwuato',
      'Obingwa',
      'Ohafia',
      'Osisioma',
      'Ugwunagbo',
      'Ukwa East',
      'Ukwa West',
      'Umuahia North',
      'Umuahia South',
      'Umu Nneochi',
    ]),
  },
  {
    code: 'AD',
    name: 'Adamawa',
    lgas: lgas([
      'Demsa',
      'Fufore',
      'Ganye',
      'Girei',
      'Gombi',
      'Guyuk',
      'Hong',
      'Jada',
      'Lamurde',
      'Madagali',
      'Maiha',
      'Mayo-Belwa',
      'Michika',
      'Mubi North',
      'Mubi South',
      'Numan',
      'Shelleng',
      'Song',
      'Toungo',
      'Yola North',
      'Yola South',
    ]),
  },
  {
    code: 'AK',
    name: 'Akwa Ibom',
    lgas: lgas([
      'Abak',
      'Eastern Obolo',
      'Eket',
      'Esit Eket',
      'Essien Udim',
      'Etim Ekpo',
      'Etinan',
      'Ibeno',
      'Ibesikpo Asutan',
      'Ibiono Ibom',
      'Ika',
      'Ikono',
      'Ikot Abasi',
      'Ikot Ekpene',
      'Ini',
      'Itu',
      'Mbo',
      'Mkpat Enin',
      'Nsit Atai',
      'Nsit Ibom',
      'Nsit Ubium',
      'Obot Akara',
      'Okobo',
      'Onna',
      'Oron',
      'Oruk Anam',
      'Udung Uko',
      'Ukanafun',
      'Uruan',
      'Urue-Offong/Oruko',
      'Uyo',
    ]),
  },
  {
    code: 'AN',
    name: 'Anambra',
    lgas: lgasWithTowns([
      { name: 'Aguata', towns: ['Aguata', 'Ekwulobia', 'Igbo-Ukwu'] },
      { name: 'Anambra East', towns: ['Anambra East', 'Otuocha'] },
      { name: 'Anambra West', towns: ['Anambra West'] },
      { name: 'Anaocha', towns: ['Anaocha', 'Neni', 'Agulu'] },
      { name: 'Awka North', towns: ['Awka North'] },
      { name: 'Awka South', towns: ['Awka', 'Amawbia', 'Nibo'] },
      { name: 'Ayamelum', towns: ['Ayamelum'] },
      { name: 'Dunukofia', towns: ['Dunukofia', 'Ukpo'] },
      { name: 'Ekwusigo', towns: ['Ekwusigo', 'Ozubulu'] },
      { name: 'Idemili North', towns: ['Idemili North', 'Ogidi', 'Nkpor'] },
      { name: 'Idemili South', towns: ['Idemili South', 'Ojoto'] },
      { name: 'Ihiala', towns: ['Ihiala', 'Okija'] },
      { name: 'Njikoka', towns: ['Njikoka', 'Abagana'] },
      { name: 'Nnewi North', towns: ['Nnewi'] },
      { name: 'Nnewi South', towns: ['Nnewi South', 'Ukpor'] },
      { name: 'Ogbaru', towns: ['Ogbaru', 'Atani'] },
      { name: 'Onitsha North', towns: ['Onitsha'] },
      { name: 'Onitsha South', towns: ['Onitsha South', 'Fegge'] },
      { name: 'Orumba North', towns: ['Orumba North', 'Ajalli'] },
      { name: 'Orumba South', towns: ['Orumba South', 'Umunze'] },
      { name: 'Oyi', towns: ['Oyi', 'Nteje'] },
    ]),
  },
  {
    code: 'BA',
    name: 'Bauchi',
    lgas: lgas([
      'Alkaleri',
      'Bauchi',
      'Bogoro',
      'Damban',
      'Darazo',
      'Dass',
      'Gamawa',
      'Ganjuwa',
      'Giade',
      'Itas/Gadau',
      "Jama'are",
      'Katagum',
      'Kirfi',
      'Misau',
      'Ningi',
      'Shira',
      'Tafawa Balewa',
      'Toro',
      'Warji',
      'Zaki',
    ]),
  },
  {
    code: 'BY',
    name: 'Bayelsa',
    lgas: lgas([
      'Brass',
      'Ekeremor',
      'Kolokuma/Opokuma',
      'Nembe',
      'Ogbia',
      'Sagbama',
      'Southern Ijaw',
      'Yenagoa',
    ]),
  },
  {
    code: 'BE',
    name: 'Benue',
    lgas: lgas([
      'Ado',
      'Agatu',
      'Apa',
      'Buruku',
      'Gboko',
      'Guma',
      'Gwer East',
      'Gwer West',
      'Katsina-Ala',
      'Konshisha',
      'Kwande',
      'Logo',
      'Makurdi',
      'Obi',
      'Ogbadibo',
      'Ohimini',
      'Oju',
      'Okpokwu',
      'Otukpo',
      'Tarka',
      'Ukum',
      'Ushongo',
      'Vandeikya',
    ]),
  },
  {
    code: 'BO',
    name: 'Borno',
    lgas: lgas([
      'Abadam',
      'Askira/Uba',
      'Bama',
      'Bayo',
      'Biu',
      'Chibok',
      'Damboa',
      'Dikwa',
      'Gubio',
      'Guzamala',
      'Gwoza',
      'Hawul',
      'Jere',
      'Kaga',
      'Kala/Balge',
      'Konduga',
      'Kukawa',
      'Kwaya Kusar',
      'Mafa',
      'Magumeri',
      'Maiduguri',
      'Marte',
      'Mobbar',
      'Monguno',
      'Ngala',
      'Nganzai',
      'Shani',
    ]),
  },
  {
    code: 'CR',
    name: 'Cross River',
    lgas: lgas([
      'Abi',
      'Akamkpa',
      'Akpabuyo',
      'Bakassi',
      'Bekwarra',
      'Biase',
      'Boki',
      'Calabar Municipal',
      'Calabar South',
      'Etung',
      'Ikom',
      'Obanliku',
      'Obubra',
      'Obudu',
      'Odukpani',
      'Ogoja',
      'Yakuur',
      'Yala',
    ]),
  },
  {
    code: 'DE',
    name: 'Delta',
    lgas: lgas([
      'Aniocha North',
      'Aniocha South',
      'Bomadi',
      'Burutu',
      'Ethiope East',
      'Ethiope West',
      'Ika North East',
      'Ika South',
      'Isoko North',
      'Isoko South',
      'Ndokwa East',
      'Ndokwa West',
      'Okpe',
      'Oshimili North',
      'Oshimili South',
      'Patani',
      'Sapele',
      'Udu',
      'Ughelli North',
      'Ughelli South',
      'Ukwuani',
      'Uvwie',
      'Warri North',
      'Warri South',
      'Warri South West',
    ]),
  },
  {
    code: 'EB',
    name: 'Ebonyi',
    lgas: lgas([
      'Abakaliki',
      'Afikpo North',
      'Afikpo South',
      'Ebonyi',
      'Ezza North',
      'Ezza South',
      'Ikwo',
      'Ishielu',
      'Ivo',
      'Izzi',
      'Ohaozara',
      'Ohaukwu',
      'Onicha',
    ]),
  },
  {
    code: 'ED',
    name: 'Edo',
    lgas: lgas([
      'Akoko-Edo',
      'Egor',
      'Esan Central',
      'Esan North-East',
      'Esan South-East',
      'Esan West',
      'Etsako Central',
      'Etsako East',
      'Etsako West',
      'Igueben',
      'Ikpoba-Okha',
      'Oredo',
      'Orhionmwon',
      'Ovia North-East',
      'Ovia South-West',
      'Owan East',
      'Owan West',
      'Uhunmwonde',
    ]),
  },
  {
    code: 'EK',
    name: 'Ekiti',
    lgas: lgas([
      'Ado Ekiti',
      'Efon',
      'Ekiti East',
      'Ekiti South-West',
      'Ekiti West',
      'Emure',
      'Gbonyin',
      'Ido Osi',
      'Ijero',
      'Ikere',
      'Ikole',
      'Ilejemeje',
      'Irepodun/Ifelodun',
      'Ise/Orun',
      'Moba',
      'Oye',
    ]),
  },
  {
    code: 'EN',
    name: 'Enugu',
    lgas: lgas([
      'Aninri',
      'Awgu',
      'Enugu East',
      'Enugu North',
      'Enugu South',
      'Ezeagu',
      'Igbo Etiti',
      'Igbo Eze North',
      'Igbo Eze South',
      'Isi Uzo',
      'Nkanu East',
      'Nkanu West',
      'Nsukka',
      'Oji River',
      'Udenu',
      'Udi',
      'Uzo-Uwani',
    ]),
  },
  {
    code: 'FC',
    name: 'Federal Capital Territory',
    lgas: lgasWithTowns([
      {
        name: 'Abaji',
        towns: ['Abaji'],
      },
      {
        name: 'Bwari',
        towns: ['Bwari', 'Kubwa', 'Dutse'],
      },
      {
        name: 'Gwagwalada',
        towns: ['Gwagwalada'],
      },
      {
        name: 'Kuje',
        towns: ['Kuje'],
      },
      {
        name: 'Kwali',
        towns: ['Kwali'],
      },
      {
        name: 'Municipal Area Council',
        towns: [
          'Central Area',
          'Garki',
          'Wuse',
          'Maitama',
          'Asokoro',
          'Guzape',
          'Jabi',
          'Utako',
          'Gwarinpa',
          'Lokogoma',
          'Lugbe',
          'Nyanya',
          'Karu',
        ],
      },
    ]),
  },
  {
    code: 'GO',
    name: 'Gombe',
    lgas: lgas([
      'Akko',
      'Balanga',
      'Billiri',
      'Dukku',
      'Funakaye',
      'Gombe',
      'Kaltungo',
      'Kwami',
      'Nafada',
      'Shongom',
      'Yamaltu/Deba',
    ]),
  },
  {
    code: 'IM',
    name: 'Imo',
    lgas: lgas([
      'Aboh Mbaise',
      'Ahiazu Mbaise',
      'Ehime Mbano',
      'Ezinihitte',
      'Ideato North',
      'Ideato South',
      'Ihitte/Uboma',
      'Ikeduru',
      'Isiala Mbano',
      'Isu',
      'Mbaitoli',
      'Ngor Okpala',
      'Njaba',
      'Nkwerre',
      'Nwangele',
      'Obowo',
      'Oguta',
      'Ohaji/Egbema',
      'Okigwe',
      'Orlu',
      'Orsu',
      'Oru East',
      'Oru West',
      'Owerri Municipal',
      'Owerri North',
      'Owerri West',
      'Unuimo',
    ]),
  },
  {
    code: 'JI',
    name: 'Jigawa',
    lgas: lgas([
      'Auyo',
      'Babura',
      'Biriniwa',
      'Birnin Kudu',
      'Buji',
      'Dutse',
      'Gagarawa',
      'Garki',
      'Gumel',
      'Guri',
      'Gwaram',
      'Gwiwa',
      'Hadejia',
      'Jahun',
      'Kafin Hausa',
      'Kazaure',
      'Kiri Kasama',
      'Kiyawa',
      'Kaugama',
      'Maigatari',
      'Malam Madori',
      'Miga',
      'Ringim',
      'Roni',
      'Sule Tankarkar',
      'Taura',
      'Yankwashi',
    ]),
  },
  {
    code: 'KD',
    name: 'Kaduna',
    lgas: lgas([
      'Birnin Gwari',
      'Chikun',
      'Giwa',
      'Igabi',
      'Ikara',
      'Jaba',
      "Jema'a",
      'Kachia',
      'Kaduna North',
      'Kaduna South',
      'Kagarko',
      'Kajuru',
      'Kaura',
      'Kauru',
      'Kubau',
      'Kudan',
      'Lere',
      'Makarfi',
      'Sabon Gari',
      'Sanga',
      'Soba',
      'Zangon Kataf',
      'Zaria',
    ]),
  },
  {
    code: 'KN',
    name: 'Kano',
    lgas: lgas([
      'Ajingi',
      'Albasu',
      'Bagwai',
      'Bebeji',
      'Bichi',
      'Bunkure',
      'Dala',
      'Dambatta',
      'Dawakin Kudu',
      'Dawakin Tofa',
      'Doguwa',
      'Fagge',
      'Gabasawa',
      'Garko',
      'Garun Mallam',
      'Gaya',
      'Gezawa',
      'Gwale',
      'Gwarzo',
      'Kabo',
      'Kano Municipal',
      'Karaye',
      'Kibiya',
      'Kiru',
      'Kumbotso',
      'Kunchi',
      'Kura',
      'Madobi',
      'Makoda',
      'Minjibir',
      'Nasarawa',
      'Rano',
      'Rimin Gado',
      'Rogo',
      'Shanono',
      'Sumaila',
      'Takai',
      'Tarauni',
      'Tofa',
      'Tsanyawa',
      'Tudun Wada',
      'Ungogo',
      'Warawa',
      'Wudil',
    ]),
  },
  {
    code: 'KT',
    name: 'Katsina',
    lgas: lgas([
      'Bakori',
      'Batagarawa',
      'Batsari',
      'Baure',
      'Bindawa',
      'Charanchi',
      'Dandume',
      'Danja',
      'Dan Musa',
      'Daura',
      'Dutsi',
      'Dutsin Ma',
      'Faskari',
      'Funtua',
      'Ingawa',
      'Jibia',
      'Kafur',
      'Kaita',
      'Kankara',
      'Kankia',
      'Katsina',
      'Kurfi',
      'Kusada',
      "Mai'Adua",
      'Malumfashi',
      'Mani',
      'Mashi',
      'Matazu',
      'Musawa',
      'Rimi',
      'Sabuwa',
      'Safana',
      'Sandamu',
      'Zango',
    ]),
  },
  {
    code: 'KE',
    name: 'Kebbi',
    lgas: lgas([
      'Aleiro',
      'Arewa Dandi',
      'Argungu',
      'Augie',
      'Bagudo',
      'Birnin Kebbi',
      'Bunza',
      'Dandi',
      'Fakai',
      'Gwandu',
      'Jega',
      'Kalgo',
      'Koko/Besse',
      'Maiyama',
      'Ngaski',
      'Sakaba',
      'Shanga',
      'Suru',
      'Wasagu/Danko',
      'Yauri',
      'Zuru',
    ]),
  },
  {
    code: 'KO',
    name: 'Kogi',
    lgas: lgas([
      'Adavi',
      'Ajaokuta',
      'Ankpa',
      'Bassa',
      'Dekina',
      'Ibaji',
      'Idah',
      'Igalamela Odolu',
      'Ijumu',
      'Kabba/Bunu',
      'Kogi',
      'Lokoja',
      'Mopa Muro',
      'Ofu',
      'Ogori/Magongo',
      'Okehi',
      'Okene',
      'Olamaboro',
      'Omala',
      'Yagba East',
      'Yagba West',
    ]),
  },
  {
    code: 'KW',
    name: 'Kwara',
    lgas: lgas([
      'Asa',
      'Baruten',
      'Edu',
      'Ekiti',
      'Ifelodun',
      'Ilorin East',
      'Ilorin South',
      'Ilorin West',
      'Irepodun',
      'Isin',
      'Kaiama',
      'Moro',
      'Offa',
      'Oke Ero',
      'Oyun',
      'Pategi',
    ]),
  },
  {
    code: 'LA',
    name: 'Lagos',
    lgas: lgasWithTowns([
      { name: 'Agege', towns: ['Agege'] },
      { name: 'Ajeromi-Ifelodun', towns: ['Ajeromi-Ifelodun', 'Ajegunle'] },
      { name: 'Alimosho', towns: ['Alimosho', 'Ikotun', 'Egbeda', 'Ijegun'] },
      { name: 'Amuwo-Odofin', towns: ['Amuwo-Odofin', 'Festac', 'Satellite Town'] },
      { name: 'Apapa', towns: ['Apapa'] },
      { name: 'Badagry', towns: ['Badagry'] },
      { name: 'Epe', towns: ['Epe'] },
      { name: 'Eti-Osa', towns: ['Eti-Osa', 'Lekki', 'Ajah', 'Victoria Island', 'Ikoyi'] },
      { name: 'Ibeju-Lekki', towns: ['Ibeju-Lekki', 'Lakowe', 'Sangotedo'] },
      { name: 'Ifako-Ijaiye', towns: ['Ifako-Ijaiye'] },
      { name: 'Ikeja', towns: ['Ikeja', 'Maryland', 'Oregun', 'Allen'] },
      { name: 'Ikorodu', towns: ['Ikorodu'] },
      { name: 'Kosofe', towns: ['Kosofe', 'Ketu', 'Mile 12'] },
      { name: 'Lagos Island', towns: ['Lagos Island', 'Marina', 'CMS'] },
      { name: 'Lagos Mainland', towns: ['Lagos Mainland', 'Yaba', 'Ebute Metta'] },
      { name: 'Mushin', towns: ['Mushin'] },
      { name: 'Ojo', towns: ['Ojo', 'Alaba'] },
      { name: 'Oshodi-Isolo', towns: ['Oshodi', 'Isolo', 'Mafoluku'] },
      { name: 'Shomolu', towns: ['Shomolu', 'Bariga'] },
      { name: 'Surulere', towns: ['Surulere'] },
    ]),
  },
  {
    code: 'NA',
    name: 'Nasarawa',
    lgas: lgas([
      'Akwanga',
      'Awe',
      'Doma',
      'Karu',
      'Keana',
      'Keffi',
      'Kokona',
      'Lafia',
      'Nasarawa',
      'Nasarawa Egon',
      'Obi',
      'Toto',
      'Wamba',
    ]),
  },
  {
    code: 'NI',
    name: 'Niger',
    lgas: lgas([
      'Agaie',
      'Agwara',
      'Bida',
      'Borgu',
      'Bosso',
      'Chanchaga',
      'Edati',
      'Gbako',
      'Gurara',
      'Katcha',
      'Kontagora',
      'Lapai',
      'Lavun',
      'Magama',
      'Mariga',
      'Mashegu',
      'Mokwa',
      'Moya',
      'Paikoro',
      'Rafi',
      'Rijau',
      'Shiroro',
      'Suleja',
      'Tafa',
      'Wushishi',
    ]),
  },
  {
    code: 'OG',
    name: 'Ogun',
    lgas: lgas([
      'Abeokuta North',
      'Abeokuta South',
      'Ado-Odo/Ota',
      'Egbado North',
      'Egbado South',
      'Ewekoro',
      'Ifo',
      'Ijebu East',
      'Ijebu North',
      'Ijebu North East',
      'Ijebu Ode',
      'Ikenne',
      'Imeko Afon',
      'Ipokia',
      'Obafemi Owode',
      'Odeda',
      'Odogbolu',
      'Ogun Waterside',
      'Remo North',
      'Shagamu',
    ]),
  },
  {
    code: 'ON',
    name: 'Ondo',
    lgas: lgas([
      'Akoko North-East',
      'Akoko North-West',
      'Akoko South-East',
      'Akoko South-West',
      'Akure North',
      'Akure South',
      'Ese Odo',
      'Idanre',
      'Ifedore',
      'Ilaje',
      'Ile Oluji/Okeigbo',
      'Irele',
      'Odigbo',
      'Okitipupa',
      'Ondo East',
      'Ondo West',
      'Ose',
      'Owo',
    ]),
  },
  {
    code: 'OS',
    name: 'Osun',
    lgas: lgas([
      'Atakunmosa East',
      'Atakunmosa West',
      'Aiyedaade',
      'Aiyedire',
      'Boluwaduro',
      'Boripe',
      'Ede North',
      'Ede South',
      'Ife Central',
      'Ife East',
      'Ife North',
      'Ife South',
      'Egbedore',
      'Ejigbo',
      'Ifedayo',
      'Ifelodun',
      'Ila',
      'Ilesa East',
      'Ilesa West',
      'Irepodun',
      'Irewole',
      'Isokan',
      'Iwo',
      'Obokun',
      'Odo Otin',
      'Ola Oluwa',
      'Olorunda',
      'Oriade',
      'Orolu',
      'Osogbo',
    ]),
  },
  {
    code: 'OY',
    name: 'Oyo',
    lgas: lgas([
      'Afijio',
      'Akinyele',
      'Atiba',
      'Atisbo',
      'Egbeda',
      'Ibadan North',
      'Ibadan North-East',
      'Ibadan North-West',
      'Ibadan South-East',
      'Ibadan South-West',
      'Ibarapa Central',
      'Ibarapa East',
      'Ibarapa North',
      'Ido',
      'Irepo',
      'Iseyin',
      'Itesiwaju',
      'Iwajowa',
      'Kajola',
      'Lagelu',
      'Ogbomosho North',
      'Ogbomosho South',
      'Ogo Oluwa',
      'Olorunsogo',
      'Oluyole',
      'Ona Ara',
      'Orelope',
      'Ori Ire',
      'Oyo East',
      'Oyo West',
      'Saki East',
      'Saki West',
      'Surulere',
    ]),
  },
  {
    code: 'PL',
    name: 'Plateau',
    lgas: lgas([
      'Barkin Ladi',
      'Bassa',
      'Bokkos',
      'Jos East',
      'Jos North',
      'Jos South',
      'Kanam',
      'Kanke',
      'Langtang North',
      'Langtang South',
      'Mangu',
      'Mikang',
      'Pankshin',
      "Qua'an Pan",
      'Riyom',
      'Shendam',
      'Wase',
    ]),
  },
  {
    code: 'RI',
    name: 'Rivers',
    lgas: lgas([
      'Abua/Odual',
      'Ahoada East',
      'Ahoada West',
      'Akuku-Toru',
      'Andoni',
      'Asari-Toru',
      'Bonny',
      'Degema',
      'Eleme',
      'Emuoha',
      'Etche',
      'Gokana',
      'Ikwerre',
      'Khana',
      'Obio/Akpor',
      'Ogba/Egbema/Ndoni',
      'Ogu/Bolo',
      'Okrika',
      'Omuma',
      'Opobo/Nkoro',
      'Oyigbo',
      'Port Harcourt',
      'Tai',
    ]),
  },
  {
    code: 'SO',
    name: 'Sokoto',
    lgas: lgas([
      'Binji',
      'Bodinga',
      'Dange Shuni',
      'Gada',
      'Goronyo',
      'Gudu',
      'Gwadabawa',
      'Illela',
      'Isa',
      'Kebbe',
      'Kware',
      'Rabah',
      'Sabon Birni',
      'Shagari',
      'Silame',
      'Sokoto North',
      'Sokoto South',
      'Tambuwal',
      'Tangaza',
      'Tureta',
      'Wamako',
      'Wurno',
      'Yabo',
    ]),
  },
  {
    code: 'TA',
    name: 'Taraba',
    lgas: lgas([
      'Ardo Kola',
      'Bali',
      'Donga',
      'Gashaka',
      'Gassol',
      'Ibi',
      'Jalingo',
      'Karim Lamido',
      'Kumi',
      'Lau',
      'Sardauna',
      'Takum',
      'Ussa',
      'Wukari',
      'Yorro',
      'Zing',
    ]),
  },
  {
    code: 'YO',
    name: 'Yobe',
    lgas: lgas([
      'Bade',
      'Bursari',
      'Damaturu',
      'Fika',
      'Fune',
      'Geidam',
      'Gujba',
      'Gulani',
      'Jakusko',
      'Karasuwa',
      'Machina',
      'Nangere',
      'Nguru',
      'Potiskum',
      'Tarmuwa',
      'Yunusari',
      'Yusufari',
    ]),
  },
  {
    code: 'ZA',
    name: 'Zamfara',
    lgas: lgas([
      'Anka',
      'Bakura',
      'Birnin Magaji/Kiyaw',
      'Bukkuyum',
      'Bungudu',
      'Gummi',
      'Gusau',
      'Kaura Namoda',
      'Maradun',
      'Maru',
      'Shinkafi',
      'Talata Mafara',
      'Chafe',
      'Zurmi',
    ]),
  },
];
